# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
recipes = Recipe.create([{dish: "Garlic Chicken", ingredients: "3 tablespoons butter, 4 skinless boneless chicken breast halves, 2 teaspoons garlic powder, 1 teaspoon seasoning salt, 1 teaspoon onion powder", preptime: 10, cooktime: 10, steps: "Melt butter in a large skillet over medium high heat. Add chicken and sprinkle with garlic powder, seasoning salt and onion powder. Saute about 10 to 15 minutes on each side, or until chicken is cooked through and juices run clear."},
  {dish: "Orange Chicken", ingredients: "3 tablespoons flour, 1/2 teaspoon garlic powder, 1/2 teaspoon salt, 1/2 teaspoon ground black pepper, 1 pound skinless boneless chicken breast halves cut into 1 inch cubes, 3 tablespoons vegetable oil, 3 celery ribs sliced, 2 green bell peppers diced, 1 onion chopped, 1/2 cup ketchup, 1/2 cup lemon juice, 1/2 cup crushed pineapple, 1/3 cup packed brown sugar", preptime: 10, cooktime: 15, steps: "Combine flour, garlic powder, salt, and black pepper in a shallow dish. Roll and coat chicken cubes in flour mixture. Heat 2 tablespoons vegetable oil in a skillet over medium-high heat. Cook and stir chicken in hot oil until not longer pink in the center and juices run clear, 8 to 10 minutes; remove and set aside. Heat 1 tablespoon vegetable oil in the same skillet over medium heat. Cook and stir celery, green peppers, and onion in heated oil until slightly tender, about 5 minutes. Return chicken to the skillet. Whisk ketchup, lemon juice, pineapple, and brown sugar in a bowl; pour into the skillet; bring to a boil. Cook and stir chicken and vegetables in sauce until heated through, 2 to 3 minutes."}])
